import React, { useState } from 'react';
import { Copy, Check, FileCode, Columns, AlignJustify, Filter } from 'lucide-react';

export default function DiffStatsBar({
  summary,
  comments = [],
  viewMode,
  onToggleViewMode,
  selectedCategory,
  onSelectCategory,
  selectedSeverity,
  onSelectSeverity,
  diffText
}) {
  const [copied, setCopied] = useState(false);

  const handleCopyMarkdown = () => {
    if (!comments || comments.length === 0) return;

    let md = `## 🤖 ReviewMate Code Review Checklist\n\n`;
    md += `**Files Changed:** ${summary?.files_changed || 1} | **Additions:** +${summary?.additions || 0} | **Deletions:** -${summary?.deletions || 0} | **Action Items:** ${comments.length}\n\n`;
    md += `### Review Checklist\n\n`;

    comments.forEach((c) => {
      const catBadge = c.category ? c.category.toUpperCase().replace('_', ' ') : 'GENERAL';
      const sevBadge = c.severity ? c.severity.charAt(0).toUpperCase() + c.severity.slice(1) : 'Suggestion';
      md += `- [ ] **[${catBadge}]** \`${c.file_path}:${c.line_number}\` *(${sevBadge})*\n`;
      md += `  > ${c.comment_text}\n`;
      if (c.code_snippet) {
        md += `  \`\`\`code\n  ${c.code_snippet}\n  \`\`\`\n`;
      }
      md += `\n`;
    });

    md += `---\n*Generated by ReviewMate (Fine-Tuned CodeT5 DLNLP Model)*\n`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  const categories = [
    { id: 'all', label: 'All Categories' },
    { id: 'bug_risk', label: 'Bug Risk' },
    { id: 'performance', label: 'Performance' },
    { id: 'edge_case', label: 'Edge Case' },
    { id: 'naming', label: 'Naming' },
    { id: 'style', label: 'Style' },
    { id: 'nit', label: 'Nit' },
  ];

  return (
    <div className="w-full bg-surface/90 border-b border-border/80 px-4 py-3 sm:px-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        
        {/* Diff stats chips */}
        <div className="flex items-center flex-wrap gap-2 text-xs font-mono">
          <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-zinc-900 border border-zinc-800 text-zinc-300">
            <FileCode className="w-3.5 h-3.5 text-zinc-400" />
            <span className="font-semibold text-zinc-100">{summary?.files_changed || 1}</span>
            <span className="text-zinc-400">file{summary?.files_changed === 1 ? '' : 's'}</span>
          </div>

          <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-emerald-950/40 border border-emerald-800/40 text-emerald-400">
            <span>+{summary?.additions || 0}</span>
            <span className="text-emerald-500/70">added</span>
          </div>

          <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-rose-950/40 border border-rose-800/40 text-rose-400">
            <span>-{summary?.deletions || 0}</span>
            <span className="text-rose-500/70">removed</span>
          </div>

          <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-indigo-950/40 border border-indigo-800/40 text-indigo-300">
            <span className="font-semibold text-indigo-200">{comments.length}</span>
            <span>comment{comments.length === 1 ? '' : 's'}</span>
          </div>
        </div>

        {/* Action buttons: View Switch & Copy All */}
        <div className="flex items-center gap-2">
          {/* View mode toggle: Unified vs Split */}
          <div className="flex items-center rounded-lg bg-zinc-900/90 border border-zinc-800 p-0.5 text-xs">
            <button
              onClick={() => onToggleViewMode('unified')}
              className={`flex items-center gap-1 px-2.5 py-1 rounded-md transition-colors ${
                viewMode === 'unified'
                  ? 'bg-zinc-800 text-zinc-100 font-medium shadow-sm'
                  : 'text-zinc-400 hover:text-zinc-200'
              }`}
              title="Unified diff view"
            >
              <AlignJustify className="w-3.5 h-3.5" />
              <span>Unified</span>
            </button>
            <button
              onClick={() => onToggleViewMode('split')}
              className={`flex items-center gap-1 px-2.5 py-1 rounded-md transition-colors ${
                viewMode === 'split'
                  ? 'bg-zinc-800 text-zinc-100 font-medium shadow-sm'
                  : 'text-zinc-400 hover:text-zinc-200'
              }`}
              title="Side-by-side split diff view"
            >
              <Columns className="w-3.5 h-3.5" />
              <span>Split</span>
            </button>
          </div>

          {/* Copy all as markdown checklist */}
          <button
            onClick={handleCopyMarkdown}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${
              copied
                ? 'bg-emerald-600/20 text-emerald-300 border-emerald-500/50'
                : 'bg-indigo-600/10 hover:bg-indigo-600/20 text-indigo-300 border-indigo-500/30 hover:border-indigo-500/50'
            }`}
            title="Copy entire review report as GitHub PR Markdown Checklist"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400 animate-bounce" />
                <span>Checklist Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-indigo-400" />
                <span>Copy for PR</span>
              </>
            )}
          </button>
        </div>

      </div>

      {/* Category filter tabs */}
      <div className="flex items-center gap-1.5 overflow-x-auto pt-2.5 text-xs no-scrollbar">
        <span className="text-[11px] text-zinc-400 flex items-center gap-1 mr-1">
          <Filter className="w-3 h-3 text-zinc-400" /> Filter:
        </span>
        {categories.map((cat) => {
          const count = cat.id === 'all' 
            ? comments.length 
            : comments.filter(c => c.category === cat.id).length;
          
          return (
            <button
              key={cat.id}
              onClick={() => onSelectCategory(cat.id)}
              className={`px-2.5 py-0.5 rounded-full whitespace-nowrap text-xs transition-colors flex items-center gap-1 ${
                selectedCategory === cat.id
                  ? 'bg-indigo-600 text-white font-medium shadow-sm shadow-indigo-500/20'
                  : 'bg-zinc-900 hover:bg-zinc-800 text-zinc-400 hover:text-zinc-200 border border-zinc-800/80'
              }`}
            >
              <span>{cat.label}</span>
              {count > 0 && (
                <span className={`text-[10px] px-1 py-0.1 rounded-full ${
                  selectedCategory === cat.id ? 'bg-indigo-700 text-indigo-100' : 'bg-zinc-800 text-zinc-400'
                }`}>
                  {count}
                </span>
              )}
            </button>
          );
        })}
      </div>

    </div>
  );
}
